---
title: "chap2"
output: html_document
date: "2026-04-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ways <- c(0, 3, 8, 9, 0)
ways / sum(ways)
```

```{r}
dbinom(6, size = 9, prob = 0.5)
```

```{r}
# グリッドの設定
p_grid <- seq(from = 0, to= 1 , length.out = 20)


# 事前確率
prior <- rep(1, 20)

# グリッドの各値に対応する尤度
likelihood <- dbinom(6, size = 9, prob = p_grid)

# 尤度×事前確率
unstd.posterior <- likelihood * prior

# 事後確率に正規化
posterior <- unstd.posterior / sum(unstd.posterior)

plot(p_grid, posterior, type = "b",
     xlab = "海の確率", ylab = "事後確率")
mtext("20 points")
```


```{r}
# 事前確率を変えてみる
prior <- ifelse(p_grid < 0.5, 0, 1)

# グリッドの各値に対応する尤度
likelihood <- dbinom(6, size = 9, prob = p_grid)

# 尤度×事前確率
unstd.posterior <- likelihood * prior

# 事後確率に正規化
posterior <- unstd.posterior / sum(unstd.posterior)

plot(p_grid, posterior, type = "b",
     xlab = "海の確率", ylab = "事後確率")
mtext("20 points")
```


```{r}
# 事前確率を変えてみる
prior <- exp(-5 * abs(p_grid - 0.5))
plot(p_grid, prior, type = "b",
     xlab = "海の確率", ylab = "事前確率")


# グリッドの各値に対応する尤度
likelihood <- dbinom(6, size = 9, prob = p_grid)

# 尤度×事前確率
unstd.posterior <- likelihood * prior

# 事後確率に正規化
posterior <- unstd.posterior / sum(unstd.posterior)

plot(p_grid, posterior, type = "b",
     xlab = "海の確率", ylab = "事後確率")
mtext("20 points")
```

```{r}
library(rethinking)

globe.qa <- quap(
  alist(
    W ~ dbinom(W + L, p),
    p ~ dunif(0, 1)
  ),
  data = list(W = 6, L = 3)
)

precis(globe.qa)
```

```{r}
W <- 6
L <- 3

curve(dbeta(x, W+1, L+1), from = 0, to = 1)

curve(dnorm(x, 0.67, 0.16), lty = 2, add = TRUE)

```

```{r}
n_samples <- 1000
p <- rep(NA, n_samples)
p[1] <- 0.5
W <- 6
L <- 3

for (i in 2:n_samples){
  p_new <- rnorm(1, p[i-1], 0.1)
  if (p_new < 0) p_new <- abs(p_new)
  if (p_new > 1) p_new <- 2 - p_new
  q0 <- dbinom(W, W + L, p[i-1])
  q1 <- dbinom(W, W + L, p_new)
  p[i] <- ifelse(runif(1) < q1/q0, p_new, p[i-1])
}

dens(p, xlim = c(0, 1))
curve(dbeta(x, W+1, L+1), lty=2, add = TRUE)
```
```{r}
n_samples <- 10000
p <- rep(NA, n_samples)
p[1] <- 0.5
W <- 6
L <- 3

for (i in 2:n_samples){
  p_new <- rnorm(1, p[i-1], 0.1)
  if (p_new < 0) p_new <- abs(p_new)
  if (p_new > 1) p_new <- 2 - p_new
  q0 <- dbinom(W, W + L, p[i-1])
  q1 <- dbinom(W, W + L, p_new)
  p[i] <- ifelse(runif(1) < q1/q0, p_new, p[i-1])
}

dens(p, xlim = c(0, 1))
curve(dbeta(x, W+1, L+1), lty=2, add = TRUE)
```
```{r}
n_samples <- 100000
p <- rep(NA, n_samples)
p[1] <- 0.5
W <- 6
L <- 3

for (i in 2:n_samples){
  p_new <- rnorm(1, p[i-1], 0.1)
  if (p_new < 0) p_new <- abs(p_new)
  if (p_new > 1) p_new <- 2 - p_new
  q0 <- dbinom(W, W + L, p[i-1])
  q1 <- dbinom(W, W + L, p_new)
  p[i] <- ifelse(runif(1) < q1/q0, p_new, p[i-1])
}

dens(p, xlim = c(0, 1))
curve(dbeta(x, W+1, L+1), lty=2, add = TRUE)
```

```{r}
# グリッドの設定
p_grid <- seq(from = 0, to= 1 , length.out = 20)

# 事前確率
prior <- rep(1, 20)
plot(p_grid, prior, type = "b",
     xlab = "海の確率", ylab = "事前確率")


# グリッドの各値に対応する尤度
likelihood <- dbinom(3, size = 3, prob = p_grid)

# 尤度×事前確率
unstd.posterior <- likelihood * prior

# 事後確率に正規化
posterior <- unstd.posterior / sum(unstd.posterior)

plot(p_grid, posterior, type = "b",
     xlab = "海の確率", ylab = "事後確率")
mtext("20 points")
```
```{r}
# グリッドの設定
p_grid <- seq(from = 0, to= 1 , length.out = 20)

# 事前確率
prior <- rep(1, 20)
plot(p_grid, prior, type = "b",
     xlab = "海の確率", ylab = "事前確率")


# グリッドの各値に対応する尤度
likelihood <- dbinom(3, size = 4, prob = p_grid)

# 尤度×事前確率
unstd.posterior <- likelihood * prior

# 事後確率に正規化
posterior <- unstd.posterior / sum(unstd.posterior)

plot(p_grid, posterior, type = "b",
     xlab = "海の確率", ylab = "事後確率")
mtext("20 points")
```
```{r}
# グリッドの設定
p_grid <- seq(from = 0, to= 1 , length.out = 20)

# 事前確率
prior <- rep(1, 20)
plot(p_grid, prior, type = "b",
     xlab = "海の確率", ylab = "事前確率")


# グリッドの各値に対応する尤度
likelihood <- dbinom(5, size = 7, prob = p_grid)

# 尤度×事前確率
unstd.posterior <- likelihood * prior

# 事後確率に正規化
posterior <- unstd.posterior / sum(unstd.posterior)

plot(p_grid, posterior, type = "b",
     xlab = "海の確率", ylab = "事後確率")
mtext("20 points")
```
```{r}
# グリッドの設定
p_grid <- seq(from = 0, to= 1 , length.out = 20)

# 事前確率
prior <- ifelse(p_grid < 0.5, 0, 1)
plot(p_grid, prior, type = "b",
     xlab = "海の確率", ylab = "事前確率")


# グリッドの各値に対応する尤度
likelihood <- dbinom(3, size = 3, prob = p_grid)

# 尤度×事前確率
unstd.posterior <- likelihood * prior

# 事後確率に正規化
posterior <- unstd.posterior / sum(unstd.posterior)

plot(p_grid, posterior, type = "b",
     xlab = "海の確率", ylab = "事後確率")
mtext("20 points")
```

```{r}
# グリッドの設定
p_grid <- seq(from = 0, to= 1 , length.out = 20)

# 事前確率
prior <- ifelse(p_grid < 0.5, 0, 1)
plot(p_grid, prior, type = "b",
     xlab = "海の確率", ylab = "事前確率")


# グリッドの各値に対応する尤度
likelihood <- dbinom(3, size = 4, prob = p_grid)

# 尤度×事前確率
unstd.posterior <- likelihood * prior

# 事後確率に正規化
posterior <- unstd.posterior / sum(unstd.posterior)

plot(p_grid, posterior, type = "b",
     xlab = "海の確率", ylab = "事後確率")
mtext("20 points")
```


```{r}
# グリッドの設定
p_grid <- seq(from = 0, to= 1 , length.out = 20)

# 事前確率
prior <- ifelse(p_grid < 0.5, 0.1, 1)
plot(p_grid, prior, type = "b",
     xlab = "海の確率", ylab = "事前確率")


# グリッドの各値に対応する尤度
likelihood <- dbinom(5, size = 7, prob = p_grid)

# 尤度×事前確率
unstd.posterior <- likelihood * prior

# 事後確率に正規化
posterior <- unstd.posterior / sum(unstd.posterior)

plot(p_grid, posterior, type = "b",
     xlab = "海の確率", ylab = "事後確率")
mtext("20 points")
```

